version : '2'

services :

    postgresqldb :
        build : "./Postgre"
        container_name: pg
        tty : true
        volumes:
         - /home/projet/postgresdata:/var/lib/postgresql/data
        ports:
         - "5432:5432"
        environment:
         POSTGRES_PASSWORD: QW228fjr78gWxU
         POSTGRES_USER : admin
         POSTGRES_DB : ezdelivery
        networks:
            ezdeliveryNetwork:
                ipv4_address: 192.168.1.22


    node:
        build : "./Node"
        container_name: api
        tty: true
        ports:
         - "8080:8080"
         - "8081:8081"
        depends_on :
         - postgresqldb
        networks:
            ezdeliveryNetwork:
                ipv4_address: 192.168.1.23

networks:
    ezdeliveryNetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.1.0/24
                  gateway: 192.168.1.1